import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { buildDefaults } from '../src/content/defaults/index'
import type { L, ProjectCard, SectionText, ServiceCard } from '../src/admin/types'

export const q = (s: string) => `'${s.replace(/'/g, "''")}'`
export const jsonb = (v: L) => q(JSON.stringify({ en: v.en ?? '', uk: v.uk ?? '' }))
/**
 * `jsonb()` normalizes an `L` (both locales, never undefined), so it can't
 * carry arbitrary JSON. This sibling emits any JSON-serializable value as a
 * jsonb literal — or SQL `null` when the section has no such value.
 */
export const jsonbAny = (v: unknown) =>
  v === null || v === undefined ? 'null' : `${q(JSON.stringify(v))}::jsonb`
const textArr = (a: string[]) => `array[${a.map(q).join(',')}]::text[]`
const bool = (b: boolean) => (b ? 'true' : 'false')
const nullable = (s: string | null | undefined) => (s ? q(s) : 'null')

function projectRows(list: 'home' | 'page', cards: ProjectCard[]): string[] {
  return cards.map((c, i) => {
    const path = c.image.kind === 'upload' ? c.image.src.split('/').slice(-2).join('/') : null
    return (
      `insert into public.projects (list,id,sort,published,title,tags,description,image_url,image_path,image_alt) values (` +
      `${q(list)},${q(c.id)},${i},${bool(c.published)},${jsonb(c.title)},${textArr(c.tags)},` +
      `${jsonb(c.description)},${nullable(c.image.src || null)},${nullable(path)},${jsonb(c.imageAlt)});`
    )
  })
}

function serviceRows(list: 'home' | 'page', cards: ServiceCard[]): string[] {
  return cards.map((c, i) =>
    `insert into public.services (list,id,sort,published,featured,title,text,icon_url,icon_path) values (` +
    `${q(list)},${q(c.id)},${i},${bool(c.published)},${bool(c.featured)},${jsonb(c.title)},` +
    `${jsonb(c.text)},${nullable(c.icon.src || null)},null);`,
  )
}

/** One `site_sections` insert, without the trailing `;`. */
export const sectionInsertSql = (s: SectionText): string =>
  `insert into public.site_sections (key,eyebrow,title,body,cta_label,cards,launch,texts,media) values (` +
  `${q(s.key)},${jsonb(s.eyebrow)},${jsonb(s.title)},${jsonb(s.body)},` +
  `${s.ctaLabel ? jsonb(s.ctaLabel) : 'null'},${jsonbAny(s.cards)},${jsonbAny(s.launch)},` +
  `${jsonbAny(s.texts)},${jsonbAny(s.media)})`

/**
 * The /services rows for `supabase/migration-2026-10-05-services-page.sql` —
 * `on conflict do nothing`, so re-running it never overwrites admin edits.
 */
export function buildServicesMigrationInserts(): string {
  return buildDefaults()
    .sections.filter((s) => s.key.startsWith('svc'))
    .map((s) => `${sectionInsertSql(s)} on conflict (key) do nothing;`)
    .join('\n') + '\n'
}

export function buildSeedSql(): string {
  const d = buildDefaults()
  const lines: string[] = [
    '-- GENERATED by scripts/gen-seed.ts — do not edit by hand. Run: npm run seed:gen',
    '-- ============================================================================',
    '-- ⚠  DESTRUCTIVE. This TRUNCATEs all content tables and reloads the bundled',
    '-- ⚠  defaults. Run ONCE, on a freshly provisioned project. Re-running AFTER',
    '-- ⚠  content has been edited in /admin will erase every edit.',
    '-- ============================================================================',
    'truncate table public.site_sections, public.seo_pages, public.projects, public.services;',
    '',
  ]

  for (const s of d.sections) {
    lines.push(`${sectionInsertSql(s)};`)
  }
  lines.push('')
  for (const e of d.seo) {
    lines.push(
      `insert into public.seo_pages (page_key,path,title,description) values (` +
      `${q(e.pageKey)},${q(e.path)},${jsonb(e.title)},${jsonb(e.description)});`,
    )
  }
  lines.push('')
  lines.push(...projectRows('home', d.projectsHome))
  lines.push(...projectRows('page', d.projectsPage))
  lines.push('')
  lines.push(...serviceRows('home', d.servicesHome))
  lines.push(...serviceRows('page', d.servicesPage))
  lines.push('')
  return lines.join('\n')
}

// Executed only when run directly (`npm run seed:gen`), not when imported by the test.
const isMain = process.argv[1] === fileURLToPath(import.meta.url)
if (isMain) {
  const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'seed.sql')
  writeFileSync(out, buildSeedSql())
  console.log(`[seed] wrote ${out}`)
}
